parameters:
  jaxon:
    app:
      classes:
        -
          directory: '%kernel.root_dir%/../jaxon/Classes'
          namespace: \Jaxon\App
          # separator: '' # '.' or '_'
          # protected: []

    lib:
      core:
        language:                      "en"
        encoding:                      "UTF-8"
        request:
          uri:                         "jaxon"
        prefix:
          class:                       ""
        debug:
          on:                          false
          verbose:                     false
        error:
          handle:                      false
        js:
          lib:
          app:
          extern:                      false
          minify:                      false

      dialogs:
        libraries:
                                       - pgwjs
        default:
          modal:                       bootstrap
          alert:                       toastr
        toastr:
          options:
            closeButton:               true
            positionClass:             "toast-top-center"
        pgwjs:
          modal:
            options:
              closeOnEscape:           true
              closeOnBackgroundClick:  true
              maxWidth:                600
