jaxon_ajax:
    resource: "@JaxonAjaxBundle/Resources/config/routing.yml"
    prefix:   /

# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation
# 
demo_home:
    path:      /
    defaults:  { _controller: AppBundle:Demo:index }

demo_jaxon:
    path:     /exp/symfony/jaxon
    defaults: { _controller: JaxonAjaxBundle:Jaxon:index }
    methods: [POST]
    